// This file is auto-generated by generate-image-components.js.
// Do not edit manually.

export const ImgBookmark = ({ ...props }) => {
  return <img src="./img_bookmark.png" alt="bookmark" {...props} />;
};

export const ImgCalender = ({ ...props }) => {
  return <img src="./img_calender.png" alt="calender" {...props} />;
};

export const ImgCheckbadge = ({ ...props }) => {
  return <img src="./img_checkbadge.png" alt="checkbadge" {...props} />;
};

export const ImgDailygraph = ({ ...props }) => {
  return <img src="./img_dailygraph.png" alt="dailygraph" {...props} />;
};

export const ImgExit = ({ ...props }) => {
  return <img src="./img_exit.png" alt="exit" {...props} />;
};

export const ImgGraph = ({ ...props }) => {
  return <img src="./img_graph.png" alt="graph" {...props} />;
};

export const ImgInfinite = ({ ...props }) => {
  return <img src="./img_infinite.png" alt="infinite" {...props} />;
};

export const ImgInvite = ({ ...props }) => {
  return <img src="./img_invite.png" alt="invite" {...props} />;
};

export const ImgInviteEmpty = ({ ...props }) => {
  return <img src="./img_invite_empty.png" alt="invite_empty" {...props} />;
};

export const ImgMedal = ({ ...props }) => {
  return <img src="./img_medal.png" alt="medal" {...props} />;
};

export const ImgMegaphoneEmpty = ({ ...props }) => {
  return <img src="./img_megaphone_empty.png" alt="megaphone_empty" {...props} />;
};

export const ImgMeteor = ({ ...props }) => {
  return <img src="./img_meteor.png" alt="meteor" {...props} />;
};

export const ImgMultiple = ({ ...props }) => {
  return <img src="./img_multiple.png" alt="multiple" {...props} />;
};

export const ImgNetworkerror = ({ ...props }) => {
  return <img src="./img_networkerror.png" alt="networkerror" {...props} />;
};

export const ImgNoteEmpty = ({ ...props }) => {
  return <img src="./img_note_empty.png" alt="note_empty" {...props} />;
};

export const ImgOx = ({ ...props }) => {
  return <img src="./img_ox.png" alt="ox" {...props} />;
};

export const ImgPageerror = ({ ...props }) => {
  return <img src="./img_pageerror.png" alt="pageerror" {...props} />;
};

export const ImgPush = ({ ...props }) => {
  return <img src="./img_push.png" alt="push" {...props} />;
};

export const ImgQuizerror = ({ ...props }) => {
  return <img src="./img_quizerror.png" alt="quizerror" {...props} />;
};

export const ImgRoundBook = ({ ...props }) => {
  return <img src="./img_round_book.png" alt="round_book" {...props} />;
};

export const ImgRoundCorrect = ({ ...props }) => {
  return <img src="./img_round_correct.png" alt="round_correct" {...props} />;
};

export const ImgRoundGoogle = ({ ...props }) => {
  return <img src="./img_round_google.png" alt="round_google" {...props} />;
};

export const ImgRoundIncorrect = ({ ...props }) => {
  return <img src="./img_round_incorrect.png" alt="round_incorrect" {...props} />;
};

export const ImgRoundKakao = ({ ...props }) => {
  return <img src="./img_round_kakao.png" alt="round_kakao" {...props} />;
};

export const ImgRoundMegaphone = ({ ...props }) => {
  return <img src="./img_round_megaphone.png" alt="round_megaphone" {...props} />;
};

export const ImgRoundMeteor = ({ ...props }) => {
  return <img src="./img_round_meteor.png" alt="round_meteor" {...props} />;
};

export const ImgRoundPicktoss = ({ ...props }) => {
  return <img src="./img_round_picktoss.png" alt="round_picktoss" {...props} />;
};

export const ImgRoundStar = ({ ...props }) => {
  return <img src="./img_round_star.png" alt="round_star" {...props} />;
};

export const ImgSpeechbubble = ({ ...props }) => {
  return <img src="./img_speechbubble.png" alt="speechbubble" {...props} />;
};

export const ImgStar = ({ ...props }) => {
  return <img src="./img_star.png" alt="star" {...props} />;
};

export const ImgStarEmpty = ({ ...props }) => {
  return <img src="./img_star_empty.png" alt="star_empty" {...props} />;
};

export const ImgStopwatch = ({ ...props }) => {
  return <img src="./img_stopwatch.png" alt="stopwatch" {...props} />;
};

export const ImgTodayquiz = ({ ...props }) => {
  return <img src="./img_todayquiz.png" alt="todayquiz" {...props} />;
};

export const ImgTreasure = ({ ...props }) => {
  return <img src="./img_treasure.png" alt="treasure" {...props} />;
};

export const ImgTreasurebox = ({ ...props }) => {
  return <img src="./img_treasurebox.png" alt="treasurebox" {...props} />;
};

