// This file is auto-generated by generate-images.cjs.
// Do not edit manually.

import imgBomb from "./img_bomb.png"
import imgBombEmpty from "./img_bomb_empty.png"
import imgBookmark from "./img_bookmark.png"
import imgCalender from "./img_calender.png"
import imgCheckbadge from "./img_checkbadge.png"
import imgConfirm from "./img_confirm.png"
import imgDailygraph from "./img_dailygraph.png"
import imgExit from "./img_exit.png"
import imgGraph from "./img_graph.png"
import imgInfinite from "./img_infinite.png"
import imgInvite from "./img_invite.png"
import imgInviteEmpty from "./img_invite_empty.png"
import imgMedal from "./img_medal.png"
import imgMegaphoneEmpty from "./img_megaphone_empty.png"
import imgMeteor from "./img_meteor.png"
import imgMultiple from "./img_multiple.png"
import imgNetworkerror from "./img_networkerror.png"
import imgNoteEmpty from "./img_note_empty.png"
import imgOx from "./img_ox.png"
import imgPageerror from "./img_pageerror.png"
import imgPush from "./img_push.png"
import imgQuizerror from "./img_quizerror.png"
import imgQuizEmpty from "./img_quiz_empty.png"
import imgRandom from "./img_random.png"
import imgRoundBook from "./img_round_book.png"
import imgRoundCorrect from "./img_round_correct.png"
import imgRoundGoogle from "./img_round_google.png"
import imgRoundIncorrect from "./img_round_incorrect.png"
import imgRoundKakao from "./img_round_kakao.png"
import imgRoundMegaphone from "./img_round_megaphone.png"
import imgRoundMeteor from "./img_round_meteor.png"
import imgRoundPicktoss from "./img_round_picktoss.png"
import imgRoundStar from "./img_round_star.png"
import imgSpeechbubble from "./img_speechbubble.png"
import imgStar from "./img_star.png"
import imgStarEmpty from "./img_star_empty.png"
import imgStopwatch from "./img_stopwatch.png"
import imgSymbol from "./img_symbol.png"
import imgTodayquiz from "./img_todayquiz.png"
import imgTreasure from "./img_treasure.png"
import imgTreasurebox from "./img_treasurebox.png"

// Type definition for image component props
type ImageComponentProps = React.ImgHTMLAttributes<HTMLImageElement>;

export const ImgBomb: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgBomb} alt="bomb" {...props} />;
};

export const ImgBombEmpty: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgBombEmpty} alt="bomb_empty" {...props} />;
};

export const ImgBookmark: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgBookmark} alt="bookmark" {...props} />;
};

export const ImgCalender: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgCalender} alt="calender" {...props} />;
};

export const ImgCheckbadge: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgCheckbadge} alt="checkbadge" {...props} />;
};

export const ImgConfirm: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgConfirm} alt="confirm" {...props} />;
};

export const ImgDailygraph: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgDailygraph} alt="dailygraph" {...props} />;
};

export const ImgExit: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgExit} alt="exit" {...props} />;
};

export const ImgGraph: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgGraph} alt="graph" {...props} />;
};

export const ImgInfinite: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgInfinite} alt="infinite" {...props} />;
};

export const ImgInvite: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgInvite} alt="invite" {...props} />;
};

export const ImgInviteEmpty: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgInviteEmpty} alt="invite_empty" {...props} />;
};

export const ImgMedal: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgMedal} alt="medal" {...props} />;
};

export const ImgMegaphoneEmpty: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgMegaphoneEmpty} alt="megaphone_empty" {...props} />;
};

export const ImgMeteor: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgMeteor} alt="meteor" {...props} />;
};

export const ImgMultiple: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgMultiple} alt="multiple" {...props} />;
};

export const ImgNetworkerror: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgNetworkerror} alt="networkerror" {...props} />;
};

export const ImgNoteEmpty: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgNoteEmpty} alt="note_empty" {...props} />;
};

export const ImgOx: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgOx} alt="ox" {...props} />;
};

export const ImgPageerror: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgPageerror} alt="pageerror" {...props} />;
};

export const ImgPush: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgPush} alt="push" {...props} />;
};

export const ImgQuizerror: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgQuizerror} alt="quizerror" {...props} />;
};

export const ImgQuizEmpty: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgQuizEmpty} alt="quiz_empty" {...props} />;
};

export const ImgRandom: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRandom} alt="random" {...props} />;
};

export const ImgRoundBook: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundBook} alt="round_book" {...props} />;
};

export const ImgRoundCorrect: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundCorrect} alt="round_correct" {...props} />;
};

export const ImgRoundGoogle: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundGoogle} alt="round_google" {...props} />;
};

export const ImgRoundIncorrect: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundIncorrect} alt="round_incorrect" {...props} />;
};

export const ImgRoundKakao: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundKakao} alt="round_kakao" {...props} />;
};

export const ImgRoundMegaphone: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundMegaphone} alt="round_megaphone" {...props} />;
};

export const ImgRoundMeteor: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundMeteor} alt="round_meteor" {...props} />;
};

export const ImgRoundPicktoss: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundPicktoss} alt="round_picktoss" {...props} />;
};

export const ImgRoundStar: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgRoundStar} alt="round_star" {...props} />;
};

export const ImgSpeechbubble: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgSpeechbubble} alt="speechbubble" {...props} />;
};

export const ImgStar: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgStar} alt="star" {...props} />;
};

export const ImgStarEmpty: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgStarEmpty} alt="star_empty" {...props} />;
};

export const ImgStopwatch: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgStopwatch} alt="stopwatch" {...props} />;
};

export const ImgSymbol: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgSymbol} alt="symbol" {...props} />;
};

export const ImgTodayquiz: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgTodayquiz} alt="todayquiz" {...props} />;
};

export const ImgTreasure: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgTreasure} alt="treasure" {...props} />;
};

export const ImgTreasurebox: React.FC<ImageComponentProps> = ({ ...props }) => {
  return <img src={imgTreasurebox} alt="treasurebox" {...props} />;
};

